#!/bin/bash
# It enables RDO deps repo when DIB_IPA_HARDWARE_RDO=1

set -eux
set -o pipefail

if [ ${DIB_IPA_HARDWARE_RDO:-0} -ne 0 ]; then
    curl -o /etc/yum.repos.d/dlrn-deps.repo https://trunk.rdoproject.org/centos9-master/dlrn-deps.repo
fi
