- project:
    templates:
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8
        - ironic-standalone-ipa-src
        - ironic-python-agent-check-image-dib-centos9
        - ironic-python-agent-check-image-dib-centos9-extra
        - ironic-python-agent-check-image-dib-centos10
        - ironic-python-agent-check-image-dib-centos10-extra
        - ironic-python-agent-check-image-dib-debian
        - ironic-python-agent-check-image-dib-debian-arm64
        - ironic-python-agent-check-image-dib-debian-extra
        - ironic-tempest-standalone-advanced
        - ipa-tempest-bios-ipmi-direct-src
        # Non-voting jobs
        - ironic-python-agent-check-image-dib-debian-bookworm:
            voting: false
        - ironic-python-agent-check-image-dib-ubuntu:
            voting: false
        - ironic-python-agent-check-image-dib-ubuntu-arm64:
            voting: false
        - ironic-python-agent-builder-tox-codespell:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8
        - ironic-standalone-ipa-src
        - ironic-python-agent-check-image-dib-centos9
        - ironic-python-agent-check-image-dib-centos9-extra
        - ironic-python-agent-check-image-dib-centos10
        - ironic-python-agent-check-image-dib-centos10-extra
        - ironic-python-agent-check-image-dib-debian
        - ironic-python-agent-check-image-dib-debian-arm64
        - ironic-python-agent-check-image-dib-debian-extra
        - ipa-tempest-bios-ipmi-direct-src
        - ironic-tempest-standalone-advanced
    post:
      jobs:
        - publish-openstack-python-branch-tarball
        - ironic-python-agent-build-image-dib-centos9:
            branches: master
        - ironic-python-agent-build-image-dib-centos10:
            branches: master
        - ironic-python-agent-build-image-dib-debian:
            branches: master
        - ironic-python-agent-build-image-dib-debian-arm64:
            branches: master
